name: CI

on:
  push:
  pull_request:

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    -
      name: Enable Corepack
      run: corepack enable
    -
      name: Checkout repo
      uses: actions/checkout@v4
    -
      id: restore
      name: Restore node_modules
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
        key: ${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ hashFiles('yarn.lock') }}-
    -
      id: install
      if: >
        steps.restore.outputs.cache-matched-key == ''
      name: Install deps
      run: yarn
    -
      if: >
        steps.install.outcome == 'success'
      name: Save node_modules
      uses: actions/cache/save@v4
      with:
        path: |
          node_modules
        key: ${{ hashFiles('yarn.lock') }}

    -
      name: Lint
      run: yarn lint
    -
      name: Test
      run: yarn test

    -
      id: build
      if: >
        github.event_name == 'push'
      name: Build
      run: yarn build
    -
      id: release
      if: >
        steps.build.outcome == 'success' &&
        github.event_name == 'push' &&
        contains('refs/heads/main,refs/heads/beta,refs/heads/alpha', github.ref)
      name: Release
      uses: ph-fritsche/action-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: OIDC
