name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.release.target_commitish}}
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: yarn publish --no-git-tag-version --new-version "${{ github.event.release.tag_name }}"
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
